dist: focal
language: node_js
node_js:
  - 19.3.0


notifications:
  email: false

before_script:
- npm run build

branches:
  only:
  - main
  - /^greenkeeper/.*$/
  except:
  - /^v\d+\.\d+\.\d+$/

after_success:
- npm install -g travis-deploy-once
- npm run travis-deploy-once "npm run semantic-release"
- npm pack

deploy:

  - provider: pages
    skip_cleanup: true
    local_dir: docs/reference
    github_token: $GITHUB_TOKEN
    on:
      tags: false
      branch: main
