[package]
name = "botserver"
version = "6.0.5"
edition = "2021"
authors = [
    "Pragmatismo.com.br <contact@pragmatismo.com.br>",
    "General Bots Community <https://github.com/GeneralBots>",
    "Rodrigo Rodriguez <rodrigorodriguez@pragmatismo.com.br>",
    "Alan Perdomo",
    "Ana Paula Gil",
    "Arenas.io",
    "Atylla L",
    "Christopher de Castilho",
    "Dario Junior",
    "David Lerner",
    "Experimentation Garage",
    "Flavio Andrade",
    "Heraldo Almeida",
    "Joao Parana",
    "Jonathas C",
    "J Ramos",
    "Lucas Picanco",
    "Marcos Velasco",
    "Matheus 39x",
    "Oerlabs Henrique",
    "Othon Lima",
    "PH Nascimento",
    "Phpussente",
    "Robson Dantas",
    "Sarah Lourenco",
    "Thi Patriota",
    "Webgus",
    "Zuilho Se",
]
description = "General Bots Server - Open-source bot platform by Pragmatismo.com.br"
license = "AGPL-3.0"
repository = "https://github.com/GeneralBots/BotServer"

[features]
desktop = ["tauri", "tauri-plugin-opener", "tauri-plugin-dialog"]
default = [ "vectordb"]
vectordb = ["qdrant-client"]
email = ["imap"]
web_automation = ["headless_chrome"]
webapp = ["tauri", "tauri-plugin-opener", "tauri-plugin-dialog"]

[dependencies]
actix-cors = "0.7"
aws-config = "0.57.0"
csv = "1.3"
actix-multipart = "0.7"
imap = { version = "3.0.0-alpha.15", optional = true }
actix-web = "4.9"
actix-ws = "0.3"
anyhow = "1.0"
async-stream = "0.3"
async-trait = "0.1"
aes-gcm = "0.10"
argon2 = "0.5"
base64 = "0.22"
bytes = "1.8"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "2.1", features = ["postgres", "uuid", "chrono", "serde_json"] }
dotenvy = "0.15"
downloader = "0.2"
env_logger = "0.11"
futures = "0.3"
futures-util = "0.3"
lettre = { version = "0.11", features = ["smtp-transport", "builder", "tokio1", "tokio1-native-tls"] }
livekit = "0.7"
include_dir = "0.7"
log = "0.4"
mailparse = "0.15"
native-tls = "0.2"
num-format = "0.4"
qdrant-client = { version = "1.12", optional = true }
rhai = { git = "https://github.com/therealprof/rhai.git", branch = "features/use-web-time" }
redis = { version = "0.27", features = ["tokio-comp"] }
regex = "1.11"
reqwest = { version = "0.12", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smartstring = "1.0"
tempfile = "3"
tokio = { version = "1.41", features = ["full"] }
tokio-stream = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
urlencoding = "2.1"
uuid = { version = "1.11", features = ["serde", "v4"] }
zip = "2.2"
time = "0.3.44"
aws-sdk-s3 = "1.108.0"
headless_chrome = { version = "1.0.18", optional = true }
rand = "0.9.2"
pdf-extract = "0.10.0"
scraper = "0.20"
sha2 = "0.10.9"
ureq = "3.1.2"
indicatif = "0.18.0"

tauri = { version = "2", features = ["unstable"], optional = true }
tauri-plugin-opener = { version = "2", optional = true }
tauri-plugin-dialog = { version = "2", optional = true }

[build-dependencies]
tauri-build = { version = "2", features = [] }

[profile.release]
lto = true  # Enables Link-Time Optimization
opt-level = "z"  # Optimizes for size instead of speed
strip = true  # Strips debug symbols
panic = "abort"  # Reduces size by removing panic unwinding
codegen-units = 1  # More aggressive optimization
