name: GBCI
run: git config --global http.sslVerify false
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: gbo
    
    steps:

    # - name: Disable SSL verification (temporary)
    #   run: git config --global http.sslVerify false

    # - uses: actions/checkout@v4

    # - name: Setup Node.js
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: '20' 
    #     cache: 'npm'       

    # - name: Copy files to deployment location
    #   run: |
    #     sudo cp -r ./* /opt/gbo/bin/BotServer/

    # - name: Install production dependencies in deployment location
    #   run: |
    #     echo "[General Bots Deployer] Building BotServer..."
    #     cd /opt/gbo/bin/BotServer
    #     sudo npm ci --production
    #     npm run build --if-present

    #     echo "[General Bots Deployer] Building default.gbui..."
    #     cd /opt/gbo/bin/BotServer/packages/default.gbui
    #     npm install
    #     npm run build
         
    - name: Restart Bots Deployer
      run: |
        echo "[General Bots Deployer] Restarting..."
        
        cd /opt/gbo/bin/BotServer

        pkill -f "node ./boot.mjs" || true
        
        npm run start  &
