name: GBCI
run: git config --global http.sslVerify false
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: gbo
    
    steps:

    - name: Disable SSL verification (temporary)
      run: git config --global http.sslVerify false

    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' 
        cache: 'npm'       

    - name: Copy files to deployment location
      run: |
        sudo cp -r ./* /opt/gbo/bin/BotServer/

    - name: Install production dependencies in deployment location
      run: |
        echo "[General Bots Deployer] Building BotServer..."
        cd /opt/gbo/bin/BotServer
        sudo npm ci --production
        npm run build --if-present

        echo "[General Bots Deployer] Building default.gbui..."
        cd /opt/gbo/bin/BotServer/packages/default.gbui
        npm config set scripts-prepend-node-path true
        npm install
        npm run build
        
        cd ../..
        rm -rf packages/default.gbui/node_modules

    - name: Kill previous Node.js process (if running)
      run: pkill -f "node dist/src/app.js" || true  # Ignore if process doesn't exist

    - name: Start Node.js in background (and persist after workflow)
      run: nohup node dist/src/app.js > /dev/null 2>&1 &